### ISSUE TITLE
unable to export Processing app

### ISSUE THREAD

**Issue by blcs79** [balandinodidonato/MyoMapper#18]
It says "Error during export". When trying to run the sketch in the IDE, it says "The function id() does not exist" and the line "if (theEvent.controller().id() == 2) ORx=orX;" is highlighted on the "bang" tab.
Mac OS X 10.9.5, Processing 2.2.1

**Comment by balandinodidonato** [comment]
Hi there, I've now released the MyoMapper's binary . You should be able to use it straight away. Please let me know how it goes.
