### ISSUE TITLE
High cpu usage?

### ISSUE THREAD

**Issue by tolgraven** [balandinodidonato/MyoMapper#19]
This app is def the easiest way out there of getting usable data out of the myo, good work! Cheers
One issue tho- for me it's using about 70% of a 4.2 GHz 5960X core (HT off) which seems... excessive. Is there any optimization to be done or is this inherent to Processing?

**Comment by balandinodidonato** [comment]
that's a good point @tolgraven . I'll look into it.

Many users reported problems with the Myo for Processig Library.
Which OS are you using? Could give me the spech of your system?

Cheers!

**Comment by tolgraven** [comment]
desktop is OS X 10.10.5, 64 GB DDR4 2600 MHz, 8-core i7 5960X OC'd to 4.2 GHz, R9 290 4GB. Obviously 70% of one core is not a problem with 8 cores but for live usage I'd be using a 4-core MBP, not sustainable if Live and Traktor is to run at the same time :/

**Comment by balandinodidonato** [comment]
I completely agree with you. I use it to do sound spatialisation, and I never had problems until now. However, you rised an important issue. I'll look into it.
Thanks to report this issue and I'll be back to you as soon as I fixed it.

Cheers!!!

**Comment by balandinodidonato** [comment]
Hi @tolgraven , here a new release. please let me know how it goes.

https://github.com/balandinodidonato/MyoMapper/releases/tag/1.1

Cheers,
Balandino.

**Comment by tolgraven** [comment]
Alright cheers, will give it a go! The option to disregard parameters should help as well :)
