### ISSUE TITLE
Show Pose/ Show Orientation Not Showing

### ISSUE THREAD

**Issue by J-Bledsoe** [balandinodidonato/MyoMapper#30]
**To Reproduce:**

    1. Launch Myo Mapper.
    2. Click Show Pose or Show Orientation but do not move the cursor off the button.

**Expected:**
  - The Orientation or Pose box shows depending on the box clicked.

**Current:**
- The toggle box clicked does not display until the cursor is moved off the toggle box.

**Comment by balandinodidonato** [comment]
Hi @J-Bledsoe, 
thanks for reporting this! That's a funny one. I'll try to look into this.
