### ISSUE TITLE
Menu bar in windows doesn't appear

### ISSUE THREAD

**Issue by balandinodidonato** [balandinodidonato/MyoMapper#36]
## To reproduce
- Compile Myo Mapper from Win branch in Windows's IDE

## Expected
- Each window will include the menu bar

## Actual
- The menu bar is not rendered

**Comment by J-Bledsoe** [comment]
Fixed in commit 07f3e11779dcabc04a0c54afea64e22f7f9379dc on the [windows branch](https://github.com/balandinodidonato/MyoMapper/tree/windows).
