### ISSUE TITLE
Missing project.pbxproj file.

### ISSUE THREAD

**Issue by NiccoloGranieri** [balandinodidonato/MyoMapper#38]
If I clone the repository from the terminal using the --recursive -submodules flags once the project is downloaded trying to open the .xcodeproj gives me the following error:

> Project /Users/.../MyoMapper/Myo Mapper/Builds/MacOSX/Myo Mapper.xcodeproj cannot be opened because it is missing its project.pbxproj file.

Same behaviour happens if I clone the .zip file directly from the MyoMapper GitHub master page.

**Comment by balandinodidonato** [comment]
As written in the documentation is always good practice to open the project from the projucer first.

Follow these instructions:
- Open `Myo Mapper.jucer`
- Verify that all modules are linked by clicking `config` -> `modules`
- Click `Save Project and Open in IDE`
- Build App
