### ISSUE TITLE
OSC messages not received by MyoMapper

### ISSUE THREAD

**Issue by najiglass** [balandinodidonato/MyoMapper#40]
Sending out OSC messages to the configured port has no effect on the Myo.
OSC Receiver set to 5425, and the test message is /myo1/vibrate "long"
When (temporarily) monitoring the port the message comes through correctly, but MyoMapper doesn't get it / doesn't send it to the Myo.
MyoMapper is sending out the OSC messages correctly (e.g. /myo1/pose "rest")

Any advice?

**Comment by balandinodidonato** [comment]
Hi @najiglass is it happening with any of the OSC messages you send to Myo Mapper or only the vibrate one?

**Comment by najiglass** [comment]
@balandinodidonato Thank you for the quick reply. I tested with "/myo1/pitch/setMin 0.2" as well but didn't see any impact on the min value in the Status window.
Let me know if there are steps I can follow to debug or provide more information on the issue.

**Comment by balandinodidonato** [comment]
which version are you using? could you test with [these](https://github.com/balandinodidonato/MyoMapper/tree/master/examples) examples?

**Comment by najiglass** [comment]
I'm on 3.1.6, reinstalled to make sure. I can't test on Max right now but the Ableton examples work fine, though they don't seem to be sending anything to Myo Mapper, only receiving from it.
Here's the file I'm using in TouchDesigner to send the OSC message, if you have the setup to test it.
[OSCtoMyo.1.toe.zip](https://github.com/balandinodidonato/MyoMapper/files/1557099/OSCtoMyo.1.toe.zip)

**Comment by balandinodidonato** [comment]
I don't have touch designer. Anyway the vibrate function does not work for now. I did disable it due to a bug I cannot fix yet. I'm working on it though.

About the scaling option you have some issues in your code. You try to set Myo Mapper's Pitch inMin value by doing `op('oscoutVib').sendOSC('/myo1/pitch/setMin', b)`
instead you should be doing `op('oscoutVib').sendOSC('/myo1/pitch/inMin', b)`

Try in this way and let me know how it goes :)

**Comment by najiglass** [comment]
Thank you! I tried with the new line to send "/myo1/pitch/inMin 0.2" but the values aren't changed in MyoMapper unfortunately. Not sure where the issue is.

Looking forward to the vibration feature!

**Comment by balandinodidonato** [comment]
sorry my bad... try `/myo1/Pitch/inMin 0.2`

**Comment by najiglass** [comment]
That works, thanks a lot!

**Comment by najiglass** [comment]
/myo1/Pitch/centre "centre" doesn't work though. Any ideas?

**Comment by balandinodidonato** [comment]
sorry my bad it should be `/myo1/Pitch/calibrate calibrate` I've updated the wiki

**Comment by najiglass** [comment]
Great, works now!
