### ISSUE TITLE
MyoMapper not sending pose to ML

### ISSUE THREAD

**Issue by Oasis14** [balandinodidonato/MyoMapper#45]
When trying to send the Hand Pose to ML the only value I receive is 0 even if the Calibration and Scaling menu shows differently. I also tested to see if this was an issue with main as well and it is.

**Comment by balandinodidonato** [comment]
Hi, I'm sorry for my delay. Thanks for this. I'll have a look at it.
I hope to fix also all windows bugs and release a Windows version too. Have you found any other bug?

**Comment by rcraig14** [comment]
I finished up my school assignment and didn't see any other bugs although I wasn't using this for all the features.
