### ISSUE TITLE
Add support for two Myo's

### ISSUE THREAD

**Issue by najiglass** [balandinodidonato/MyoMapper#47]
Is it possible to currently run two Myo's?

**Comment by balandinodidonato** [comment]
Hi @najiglass , yes it is:
- Duplicate the Myo Mapper application you have already installed.
- Rename it with a different name, eg. "Myo Mapper 2"
- Launch a first Myo Mapper instance and select Myo 1
- Launch the second Myo Mapper instance and select Myo 2

I know, it is not very user-friendly. The next version will embed a function in the GUI.

Cheers,
Balandino.

**Comment by najiglass** [comment]
Amazing, thanks!
